
spring:
  profiles:
    active: dev
---
debug: true
spring:
  profiles: dev
  messages:
     basename: i18n.message
    # 国际化文件夹路径
     encoding: utf-8
    # 编码格式
demo:
 age: 22
 name: dev
 email: aaaaabbbbb@com.cn
 boss: false
server:
  servlet:
    context-path: /
logging:
  level:
    pers.adlered.voter: debug


---

spring:
  profiles: prod
demo:
  age: 24
  name: prod
  email: aaaaabbbbb@com.cn
  boss: false
