package pers.adlered.voter.domain;

public class VoteDetail {


    /***
     *

     * han
     *
     * **/
     private Vote1 vote;
    public Vote1 getVote() {
        return vote;
    }

    public void setVote(Vote1 vote) {
        this.vote = vote;
    }
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Voter_Vote_Detail.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Voter_Vote_Detail.VID
     *
     * @mbg.generated
     */
    private Integer vid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Voter_Vote_Detail.Detail
     *
     * @mbg.generated
     */
    private String detail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Voter_Vote_Detail.Sno
     *
     * @mbg.generated
     */
    private Integer sno;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote_Detail
     *
     * @mbg.generated
     */
    public VoteDetail(Integer id, Integer vid, String detail, Integer sno) {
        this.id = id;
        this.vid = vid;
        this.detail = detail;
        this.sno = sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote_Detail
     *
     * @mbg.generated
     */
    public VoteDetail() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Voter_Vote_Detail.ID
     *
     * @return the value of Voter_Vote_Detail.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Voter_Vote_Detail.ID
     *
     * @param id the value for Voter_Vote_Detail.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Voter_Vote_Detail.VID
     *
     * @return the value of Voter_Vote_Detail.VID
     *
     * @mbg.generated
     */
    public Integer getVid() {
        return vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Voter_Vote_Detail.VID
     *
     * @param vid the value for Voter_Vote_Detail.VID
     *
     * @mbg.generated
     */
    public void setVid(Integer vid) {
        this.vid = vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Voter_Vote_Detail.Detail
     *
     * @return the value of Voter_Vote_Detail.Detail
     *
     * @mbg.generated
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Voter_Vote_Detail.Detail
     *
     * @param detail the value for Voter_Vote_Detail.Detail
     *
     * @mbg.generated
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Voter_Vote_Detail.Sno
     *
     * @return the value of Voter_Vote_Detail.Sno
     *
     * @mbg.generated
     */
    public Integer getSno() {
        return sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Voter_Vote_Detail.Sno
     *
     * @param sno the value for Voter_Vote_Detail.Sno
     *
     * @mbg.generated
     */
    public void setSno(Integer sno) {
        this.sno = sno;
    }
}