package pers.adlered.voter.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class VoteTokenExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Voter_Vote_Token
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Voter_Vote_Token
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Voter_Vote_Token
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote_Token
     *
     * @mbg.generated
     */
    public VoteTokenExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote_Token
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote_Token
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote_Token
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote_Token
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote_Token
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote_Token
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote_Token
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote_Token
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote_Token
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote_Token
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Voter_Vote_Token
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andVidIsNull() {
            addCriterion("VID is null");
            return (Criteria) this;
        }

        public Criteria andVidIsNotNull() {
            addCriterion("VID is not null");
            return (Criteria) this;
        }

        public Criteria andVidEqualTo(Integer value) {
            addCriterion("VID =", value, "vid");
            return (Criteria) this;
        }

        public Criteria andVidNotEqualTo(Integer value) {
            addCriterion("VID <>", value, "vid");
            return (Criteria) this;
        }

        public Criteria andVidGreaterThan(Integer value) {
            addCriterion("VID >", value, "vid");
            return (Criteria) this;
        }

        public Criteria andVidGreaterThanOrEqualTo(Integer value) {
            addCriterion("VID >=", value, "vid");
            return (Criteria) this;
        }

        public Criteria andVidLessThan(Integer value) {
            addCriterion("VID <", value, "vid");
            return (Criteria) this;
        }

        public Criteria andVidLessThanOrEqualTo(Integer value) {
            addCriterion("VID <=", value, "vid");
            return (Criteria) this;
        }

        public Criteria andVidIn(List<Integer> values) {
            addCriterion("VID in", values, "vid");
            return (Criteria) this;
        }

        public Criteria andVidNotIn(List<Integer> values) {
            addCriterion("VID not in", values, "vid");
            return (Criteria) this;
        }

        public Criteria andVidBetween(Integer value1, Integer value2) {
            addCriterion("VID between", value1, value2, "vid");
            return (Criteria) this;
        }

        public Criteria andVidNotBetween(Integer value1, Integer value2) {
            addCriterion("VID not between", value1, value2, "vid");
            return (Criteria) this;
        }

        public Criteria andTokenIsNull() {
            addCriterion("Token is null");
            return (Criteria) this;
        }

        public Criteria andTokenIsNotNull() {
            addCriterion("Token is not null");
            return (Criteria) this;
        }

        public Criteria andTokenEqualTo(String value) {
            addCriterion("Token =", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenNotEqualTo(String value) {
            addCriterion("Token <>", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenGreaterThan(String value) {
            addCriterion("Token >", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenGreaterThanOrEqualTo(String value) {
            addCriterion("Token >=", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenLessThan(String value) {
            addCriterion("Token <", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenLessThanOrEqualTo(String value) {
            addCriterion("Token <=", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenLike(String value) {
            addCriterion("Token like", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenNotLike(String value) {
            addCriterion("Token not like", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenIn(List<String> values) {
            addCriterion("Token in", values, "token");
            return (Criteria) this;
        }

        public Criteria andTokenNotIn(List<String> values) {
            addCriterion("Token not in", values, "token");
            return (Criteria) this;
        }

        public Criteria andTokenBetween(String value1, String value2) {
            addCriterion("Token between", value1, value2, "token");
            return (Criteria) this;
        }

        public Criteria andTokenNotBetween(String value1, String value2) {
            addCriterion("Token not between", value1, value2, "token");
            return (Criteria) this;
        }

        public Criteria andSelectionIsNull() {
            addCriterion("Selection is null");
            return (Criteria) this;
        }

        public Criteria andSelectionIsNotNull() {
            addCriterion("Selection is not null");
            return (Criteria) this;
        }

        public Criteria andSelectionEqualTo(String value) {
            addCriterion("Selection =", value, "selection");
            return (Criteria) this;
        }

        public Criteria andSelectionNotEqualTo(String value) {
            addCriterion("Selection <>", value, "selection");
            return (Criteria) this;
        }

        public Criteria andSelectionGreaterThan(String value) {
            addCriterion("Selection >", value, "selection");
            return (Criteria) this;
        }

        public Criteria andSelectionGreaterThanOrEqualTo(String value) {
            addCriterion("Selection >=", value, "selection");
            return (Criteria) this;
        }

        public Criteria andSelectionLessThan(String value) {
            addCriterion("Selection <", value, "selection");
            return (Criteria) this;
        }

        public Criteria andSelectionLessThanOrEqualTo(String value) {
            addCriterion("Selection <=", value, "selection");
            return (Criteria) this;
        }

        public Criteria andSelectionLike(String value) {
            addCriterion("Selection like", value, "selection");
            return (Criteria) this;
        }

        public Criteria andSelectionNotLike(String value) {
            addCriterion("Selection not like", value, "selection");
            return (Criteria) this;
        }

        public Criteria andSelectionIn(List<String> values) {
            addCriterion("Selection in", values, "selection");
            return (Criteria) this;
        }

        public Criteria andSelectionNotIn(List<String> values) {
            addCriterion("Selection not in", values, "selection");
            return (Criteria) this;
        }

        public Criteria andSelectionBetween(String value1, String value2) {
            addCriterion("Selection between", value1, value2, "selection");
            return (Criteria) this;
        }

        public Criteria andSelectionNotBetween(String value1, String value2) {
            addCriterion("Selection not between", value1, value2, "selection");
            return (Criteria) this;
        }

        public Criteria andMd5VIsNull() {
            addCriterion("md5_v is null");
            return (Criteria) this;
        }

        public Criteria andMd5VIsNotNull() {
            addCriterion("md5_v is not null");
            return (Criteria) this;
        }

        public Criteria andMd5VEqualTo(String value) {
            addCriterion("md5_v =", value, "md5V");
            return (Criteria) this;
        }

        public Criteria andMd5VNotEqualTo(String value) {
            addCriterion("md5_v <>", value, "md5V");
            return (Criteria) this;
        }

        public Criteria andMd5VGreaterThan(String value) {
            addCriterion("md5_v >", value, "md5V");
            return (Criteria) this;
        }

        public Criteria andMd5VGreaterThanOrEqualTo(String value) {
            addCriterion("md5_v >=", value, "md5V");
            return (Criteria) this;
        }

        public Criteria andMd5VLessThan(String value) {
            addCriterion("md5_v <", value, "md5V");
            return (Criteria) this;
        }

        public Criteria andMd5VLessThanOrEqualTo(String value) {
            addCriterion("md5_v <=", value, "md5V");
            return (Criteria) this;
        }

        public Criteria andMd5VLike(String value) {
            addCriterion("md5_v like", value, "md5V");
            return (Criteria) this;
        }

        public Criteria andMd5VNotLike(String value) {
            addCriterion("md5_v not like", value, "md5V");
            return (Criteria) this;
        }

        public Criteria andMd5VIn(List<String> values) {
            addCriterion("md5_v in", values, "md5V");
            return (Criteria) this;
        }

        public Criteria andMd5VNotIn(List<String> values) {
            addCriterion("md5_v not in", values, "md5V");
            return (Criteria) this;
        }

        public Criteria andMd5VBetween(String value1, String value2) {
            addCriterion("md5_v between", value1, value2, "md5V");
            return (Criteria) this;
        }

        public Criteria andMd5VNotBetween(String value1, String value2) {
            addCriterion("md5_v not between", value1, value2, "md5V");
            return (Criteria) this;
        }

        public Criteria andMd5MIsNull() {
            addCriterion("md5_m is null");
            return (Criteria) this;
        }

        public Criteria andMd5MIsNotNull() {
            addCriterion("md5_m is not null");
            return (Criteria) this;
        }

        public Criteria andMd5MEqualTo(String value) {
            addCriterion("md5_m =", value, "md5M");
            return (Criteria) this;
        }

        public Criteria andMd5MNotEqualTo(String value) {
            addCriterion("md5_m <>", value, "md5M");
            return (Criteria) this;
        }

        public Criteria andMd5MGreaterThan(String value) {
            addCriterion("md5_m >", value, "md5M");
            return (Criteria) this;
        }

        public Criteria andMd5MGreaterThanOrEqualTo(String value) {
            addCriterion("md5_m >=", value, "md5M");
            return (Criteria) this;
        }

        public Criteria andMd5MLessThan(String value) {
            addCriterion("md5_m <", value, "md5M");
            return (Criteria) this;
        }

        public Criteria andMd5MLessThanOrEqualTo(String value) {
            addCriterion("md5_m <=", value, "md5M");
            return (Criteria) this;
        }

        public Criteria andMd5MLike(String value) {
            addCriterion("md5_m like", value, "md5M");
            return (Criteria) this;
        }

        public Criteria andMd5MNotLike(String value) {
            addCriterion("md5_m not like", value, "md5M");
            return (Criteria) this;
        }

        public Criteria andMd5MIn(List<String> values) {
            addCriterion("md5_m in", values, "md5M");
            return (Criteria) this;
        }

        public Criteria andMd5MNotIn(List<String> values) {
            addCriterion("md5_m not in", values, "md5M");
            return (Criteria) this;
        }

        public Criteria andMd5MBetween(String value1, String value2) {
            addCriterion("md5_m between", value1, value2, "md5M");
            return (Criteria) this;
        }

        public Criteria andMd5MNotBetween(String value1, String value2) {
            addCriterion("md5_m not between", value1, value2, "md5M");
            return (Criteria) this;
        }

        public Criteria andCrcIsNull() {
            addCriterion("crc is null");
            return (Criteria) this;
        }

        public Criteria andCrcIsNotNull() {
            addCriterion("crc is not null");
            return (Criteria) this;
        }

        public Criteria andCrcEqualTo(String value) {
            addCriterion("crc =", value, "crc");
            return (Criteria) this;
        }

        public Criteria andCrcNotEqualTo(String value) {
            addCriterion("crc <>", value, "crc");
            return (Criteria) this;
        }

        public Criteria andCrcGreaterThan(String value) {
            addCriterion("crc >", value, "crc");
            return (Criteria) this;
        }

        public Criteria andCrcGreaterThanOrEqualTo(String value) {
            addCriterion("crc >=", value, "crc");
            return (Criteria) this;
        }

        public Criteria andCrcLessThan(String value) {
            addCriterion("crc <", value, "crc");
            return (Criteria) this;
        }

        public Criteria andCrcLessThanOrEqualTo(String value) {
            addCriterion("crc <=", value, "crc");
            return (Criteria) this;
        }

        public Criteria andCrcLike(String value) {
            addCriterion("crc like", value, "crc");
            return (Criteria) this;
        }

        public Criteria andCrcNotLike(String value) {
            addCriterion("crc not like", value, "crc");
            return (Criteria) this;
        }

        public Criteria andCrcIn(List<String> values) {
            addCriterion("crc in", values, "crc");
            return (Criteria) this;
        }

        public Criteria andCrcNotIn(List<String> values) {
            addCriterion("crc not in", values, "crc");
            return (Criteria) this;
        }

        public Criteria andCrcBetween(String value1, String value2) {
            addCriterion("crc between", value1, value2, "crc");
            return (Criteria) this;
        }

        public Criteria andCrcNotBetween(String value1, String value2) {
            addCriterion("crc not between", value1, value2, "crc");
            return (Criteria) this;
        }

        public Criteria andVotedateIsNull() {
            addCriterion("VoteDate is null");
            return (Criteria) this;
        }

        public Criteria andVotedateIsNotNull() {
            addCriterion("VoteDate is not null");
            return (Criteria) this;
        }

        public Criteria andVotedateEqualTo(Date value) {
            addCriterionForJDBCDate("VoteDate =", value, "votedate");
            return (Criteria) this;
        }

        public Criteria andVotedateNotEqualTo(Date value) {
            addCriterionForJDBCDate("VoteDate <>", value, "votedate");
            return (Criteria) this;
        }

        public Criteria andVotedateGreaterThan(Date value) {
            addCriterionForJDBCDate("VoteDate >", value, "votedate");
            return (Criteria) this;
        }

        public Criteria andVotedateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("VoteDate >=", value, "votedate");
            return (Criteria) this;
        }

        public Criteria andVotedateLessThan(Date value) {
            addCriterionForJDBCDate("VoteDate <", value, "votedate");
            return (Criteria) this;
        }

        public Criteria andVotedateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("VoteDate <=", value, "votedate");
            return (Criteria) this;
        }

        public Criteria andVotedateIn(List<Date> values) {
            addCriterionForJDBCDate("VoteDate in", values, "votedate");
            return (Criteria) this;
        }

        public Criteria andVotedateNotIn(List<Date> values) {
            addCriterionForJDBCDate("VoteDate not in", values, "votedate");
            return (Criteria) this;
        }

        public Criteria andVotedateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("VoteDate between", value1, value2, "votedate");
            return (Criteria) this;
        }

        public Criteria andVotedateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("VoteDate not between", value1, value2, "votedate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Voter_Vote_Token
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Voter_Vote_Token
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}