package pers.adlered.voter.domain;

public class Vote1 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Voter_Vote.VID
     *
     * @mbg.generated
     */
    private Integer vid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Voter_Vote.Title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Voter_Vote.Describe
     *
     * @mbg.generated
     */
    private String describe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Voter_Vote.Selection
     *
     * @mbg.generated
     */
    private String selection;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Voter_Vote.Type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Voter_Vote.Limit
     *
     * @mbg.generated
     */
    private Integer limit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Voter_Vote.Pass
     *
     * @mbg.generated
     */
    private String pass;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote
     *
     * @mbg.generated
     */
    public Vote1(Integer vid, String title, String describe, String selection, Integer type, Integer limit, String pass) {
        this.vid = vid;
        this.title = title;
        this.describe = describe;
        this.selection = selection;
        this.type = type;
        this.limit = limit;
        this.pass = pass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote
     *
     * @mbg.generated
     */
    public Vote1() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Voter_Vote.VID
     *
     * @return the value of Voter_Vote.VID
     *
     * @mbg.generated
     */
    public Integer getVid() {
        return vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Voter_Vote.VID
     *
     * @param vid the value for Voter_Vote.VID
     *
     * @mbg.generated
     */
    public void setVid(Integer vid) {
        this.vid = vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Voter_Vote.Title
     *
     * @return the value of Voter_Vote.Title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Voter_Vote.Title
     *
     * @param title the value for Voter_Vote.Title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Voter_Vote.Describe
     *
     * @return the value of Voter_Vote.Describe
     *
     * @mbg.generated
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Voter_Vote.Describe
     *
     * @param describe the value for Voter_Vote.Describe
     *
     * @mbg.generated
     */
    public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Voter_Vote.Selection
     *
     * @return the value of Voter_Vote.Selection
     *
     * @mbg.generated
     */
    public String getSelection() {
        return selection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Voter_Vote.Selection
     *
     * @param selection the value for Voter_Vote.Selection
     *
     * @mbg.generated
     */
    public void setSelection(String selection) {
        this.selection = selection == null ? null : selection.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Voter_Vote.Type
     *
     * @return the value of Voter_Vote.Type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Voter_Vote.Type
     *
     * @param type the value for Voter_Vote.Type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Voter_Vote.Limit
     *
     * @return the value of Voter_Vote.Limit
     *
     * @mbg.generated
     */
    public Integer getLimit() {
        return limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Voter_Vote.Limit
     *
     * @param limit the value for Voter_Vote.Limit
     *
     * @mbg.generated
     */
    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Voter_Vote.Pass
     *
     * @return the value of Voter_Vote.Pass
     *
     * @mbg.generated
     */
    public String getPass() {
        return pass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Voter_Vote.Pass
     *
     * @param pass the value for Voter_Vote.Pass
     *
     * @mbg.generated
     */
    public void setPass(String pass) {
        this.pass = pass == null ? null : pass.trim();
    }
}