package pers.adlered.voter.domain;

import java.util.List;

public class Vote1 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Voter_Vote.VID
     *
     * @mbg.generated
     */
    private Integer vid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Voter_Vote.Title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Voter_Vote.Describes
     *
     * @mbg.generated
     */
    private String describes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Voter_Vote.Selection
     *
     * @mbg.generated
     */
    private String selection;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Voter_Vote.Type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Voter_Vote.Limits
     *
     * @mbg.generated
     */
    private Integer limits;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Voter_Vote.Pass
     *
     * @mbg.generated
     */
    private String pass;

    /**
     *
     * @han
     */
    public List<VoteDetail> getDetails() {
        return details;
    }

    public void setDetails(List<VoteDetail> details) {
        this.details = details;
    }

    private List<VoteDetail> details;
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote
     *
     * @mbg.generated
     */
    public Vote1(Integer vid, String title, String describes, String selection, Integer type, Integer limits, String pass) {
        this.vid = vid;
        this.title = title;
        this.describes = describes;
        this.selection = selection;
        this.type = type;
        this.limits = limits;
        this.pass = pass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote
     *
     * @mbg.generated
     */
    public Vote1() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Voter_Vote.VID
     *
     * @return the value of Voter_Vote.VID
     *
     * @mbg.generated
     */
    public Integer getVid() {
        return vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Voter_Vote.VID
     *
     * @param vid the value for Voter_Vote.VID
     *
     * @mbg.generated
     */
    public void setVid(Integer vid) {
        this.vid = vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Voter_Vote.Title
     *
     * @return the value of Voter_Vote.Title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Voter_Vote.Title
     *
     * @param title the value for Voter_Vote.Title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Voter_Vote.Describes
     *
     * @return the value of Voter_Vote.Describes
     *
     * @mbg.generated
     */
    public String getDescribes() {
        return describes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Voter_Vote.Describes
     *
     * @param describes the value for Voter_Vote.Describes
     *
     * @mbg.generated
     */
    public void setDescribes(String describes) {
        this.describes = describes == null ? null : describes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Voter_Vote.Selection
     *
     * @return the value of Voter_Vote.Selection
     *
     * @mbg.generated
     */
    public String getSelection() {
        return selection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Voter_Vote.Selection
     *
     * @param selection the value for Voter_Vote.Selection
     *
     * @mbg.generated
     */
    public void setSelection(String selection) {
        this.selection = selection == null ? null : selection.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Voter_Vote.Type
     *
     * @return the value of Voter_Vote.Type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Voter_Vote.Type
     *
     * @param type the value for Voter_Vote.Type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Voter_Vote.Limits
     *
     * @return the value of Voter_Vote.Limits
     *
     * @mbg.generated
     */
    public Integer getLimits() {
        return limits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Voter_Vote.Limits
     *
     * @param limits the value for Voter_Vote.Limits
     *
     * @mbg.generated
     */
    public void setLimits(Integer limits) {
        this.limits = limits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Voter_Vote.Pass
     *
     * @return the value of Voter_Vote.Pass
     *
     * @mbg.generated
     */
    public String getPass() {
        return pass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Voter_Vote.Pass
     *
     * @param pass the value for Voter_Vote.Pass
     *
     * @mbg.generated
     */
    public void setPass(String pass) {
        this.pass = pass == null ? null : pass.trim();
    }
}