package pers.adlered.voter.service;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Service;
import pers.adlered.voter.domain.Vote1;
import pers.adlered.voter.domain.Vote1Example;

import java.util.List;
@Service
public interface Vote1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote
     *
     * @mbg.generated
     */
    @SelectProvider(type=Vote1SqlProvider.class, method="countByExample")
    long countByExample(Vote1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote
     *
     * @mbg.generated
     */
    @DeleteProvider(type=Vote1SqlProvider.class, method="deleteByExample")
    int deleteByExample(Vote1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote
     *
     * @mbg.generated
     */
    @Delete({
        "delete from Voter_Vote",
        "where VID = #{vid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer vid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote
     *
     * @mbg.generated
     */
    @Insert({
        "insert into Voter_Vote (Title, Describes, ",
        "Selection, Type, ",
        "Limits, Pass)",
        "values (#{title,jdbcType=VARCHAR}, #{describes,jdbcType=VARCHAR}, ",
        "#{selection,jdbcType=VARCHAR}, #{type,jdbcType=INTEGER}, ",
        "#{limits,jdbcType=INTEGER}, #{pass,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="vid", before=false, resultType=Integer.class)
    int insert(Vote1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote
     *
     * @mbg.generated
     */
    @InsertProvider(type=Vote1SqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="vid", before=false, resultType=Integer.class)
    int insertSelective(Vote1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote
     *
     * @mbg.generated
     */
    @SelectProvider(type=Vote1SqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="VID", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="Title", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="Describes", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="Selection", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="Type", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="Limits", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="Pass", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<Vote1> selectByExample(Vote1Example example);

    /**

     *
     * @han
     */
    @SelectProvider(type=Vote1SqlProvider.class, method="selectByExample")
    @ConstructorArgs({
            @Arg(column="VID", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
            @Arg(column="Title", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="Describes", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="Selection", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="Type", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
            @Arg(column="Limits", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
            @Arg(column="Pass", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    @Results( {@Result(property="details",column="VID",
            many=@Many(select="pers.adlered.voter.service.VoteDetailMapper.selectByVid"))
             })
    List<Vote1> selectDetailByExample(Vote1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "VID, Title, Describes, Selection, Type, Limits, Pass",
        "from Voter_Vote",
        "where VID = #{vid,jdbcType=INTEGER}"
    })
    @ConstructorArgs({
        @Arg(column="VID", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="Title", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="Describes", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="Selection", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="Type", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="Limits", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="Pass", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    Vote1 selectByPrimaryKey(Integer vid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote
     *
     * @mbg.generated
     */
    @UpdateProvider(type=Vote1SqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Vote1 record, @Param("example") Vote1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote
     *
     * @mbg.generated
     */
    @UpdateProvider(type=Vote1SqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Vote1 record, @Param("example") Vote1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote
     *
     * @mbg.generated
     */
    @UpdateProvider(type=Vote1SqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Vote1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote
     *
     * @mbg.generated
     */
    @Update({
        "update Voter_Vote",
        "set Title = #{title,jdbcType=VARCHAR},",
          "Describes = #{describes,jdbcType=VARCHAR},",
          "Selection = #{selection,jdbcType=VARCHAR},",
          "Type = #{type,jdbcType=INTEGER},",
          "Limits = #{limits,jdbcType=INTEGER},",
          "Pass = #{pass,jdbcType=VARCHAR}",
        "where VID = #{vid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Vote1 record);
}