package pers.adlered.voter.service;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import pers.adlered.voter.domain.VoteDetail;
import pers.adlered.voter.domain.VoteDetailExample;

import java.util.List;

public interface VoteDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote_Detail
     *
     * @mbg.generated
     */
    @SelectProvider(type=VoteDetailSqlProvider.class, method="countByExample")
    long countByExample(VoteDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote_Detail
     *
     * @mbg.generated
     */
    @DeleteProvider(type=VoteDetailSqlProvider.class, method="deleteByExample")
    int deleteByExample(VoteDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote_Detail
     *
     * @mbg.generated
     */
    @Insert({
        "insert into Voter_Vote_Detail (VID, Detail, ",
        "Sno)",
        "values (#{vid,jdbcType=INTEGER}, #{detail,jdbcType=VARCHAR}, ",
        "#{sno,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(VoteDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote_Detail
     *
     * @mbg.generated
     */
    @InsertProvider(type=VoteDetailSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(VoteDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote_Detail
     *
     * @mbg.generated
     */
    @SelectProvider(type=VoteDetailSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="ID", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="VID", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="Detail", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="Sno", javaType=Integer.class, jdbcType=JdbcType.INTEGER)
    })
    List<VoteDetail> selectByExample(VoteDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote_Detail
     *
     * @mbg.generated
     */
    @UpdateProvider(type=VoteDetailSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") VoteDetail record, @Param("example") VoteDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote_Detail
     *
     * @mbg.generated
     */
    @UpdateProvider(type=VoteDetailSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") VoteDetail record, @Param("example") VoteDetailExample example);
}