package pers.adlered.voter.service;

import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;
import pers.adlered.voter.domain.VoteToken;
import pers.adlered.voter.domain.VoteTokenExample.Criteria;
import pers.adlered.voter.domain.VoteTokenExample.Criterion;
import pers.adlered.voter.domain.VoteTokenExample;

public class VoteTokenSqlProvider {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote_Token
     *
     * @mbg.generated
     */
    public String countByExample(VoteTokenExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("Voter_Vote_Token");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote_Token
     *
     * @mbg.generated
     */
    public String deleteByExample(VoteTokenExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("Voter_Vote_Token");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote_Token
     *
     * @mbg.generated
     */
    public String insertSelective(VoteToken record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("Voter_Vote_Token");
        
        if (record.getVid() != null) {
            sql.VALUES("VID", "#{vid,jdbcType=INTEGER}");
        }
        
        if (record.getToken() != null) {
            sql.VALUES("Token", "#{token,jdbcType=VARCHAR}");
        }
        
        if (record.getSelection() != null) {
            sql.VALUES("Selection", "#{selection,jdbcType=VARCHAR}");
        }
        
        if (record.getMd5V() != null) {
            sql.VALUES("md5_v", "#{md5V,jdbcType=VARCHAR}");
        }
        
        if (record.getMd5M() != null) {
            sql.VALUES("md5_m", "#{md5M,jdbcType=VARCHAR}");
        }
        
        if (record.getCrc() != null) {
            sql.VALUES("crc", "#{crc,jdbcType=VARCHAR}");
        }
        
        if (record.getVotedate() != null) {
            sql.VALUES("VoteDate", "#{votedate,jdbcType=DATE}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote_Token
     *
     * @mbg.generated
     */
    public String selectByExample(VoteTokenExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("ID");
        } else {
            sql.SELECT("ID");
        }
        sql.SELECT("VID");
        sql.SELECT("Token");
        sql.SELECT("Selection");
        sql.SELECT("md5_v");
        sql.SELECT("md5_m");
        sql.SELECT("crc");
        sql.SELECT("VoteDate");
        sql.FROM("Voter_Vote_Token");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote_Token
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        VoteToken record = (VoteToken) parameter.get("record");
        VoteTokenExample example = (VoteTokenExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("Voter_Vote_Token");
        
        if (record.getId() != null) {
            sql.SET("ID = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getVid() != null) {
            sql.SET("VID = #{record.vid,jdbcType=INTEGER}");
        }
        
        if (record.getToken() != null) {
            sql.SET("Token = #{record.token,jdbcType=VARCHAR}");
        }
        
        if (record.getSelection() != null) {
            sql.SET("Selection = #{record.selection,jdbcType=VARCHAR}");
        }
        
        if (record.getMd5V() != null) {
            sql.SET("md5_v = #{record.md5V,jdbcType=VARCHAR}");
        }
        
        if (record.getMd5M() != null) {
            sql.SET("md5_m = #{record.md5M,jdbcType=VARCHAR}");
        }
        
        if (record.getCrc() != null) {
            sql.SET("crc = #{record.crc,jdbcType=VARCHAR}");
        }
        
        if (record.getVotedate() != null) {
            sql.SET("VoteDate = #{record.votedate,jdbcType=DATE}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote_Token
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("Voter_Vote_Token");
        
        sql.SET("ID = #{record.id,jdbcType=INTEGER}");
        sql.SET("VID = #{record.vid,jdbcType=INTEGER}");
        sql.SET("Token = #{record.token,jdbcType=VARCHAR}");
        sql.SET("Selection = #{record.selection,jdbcType=VARCHAR}");
        sql.SET("md5_v = #{record.md5V,jdbcType=VARCHAR}");
        sql.SET("md5_m = #{record.md5M,jdbcType=VARCHAR}");
        sql.SET("crc = #{record.crc,jdbcType=VARCHAR}");
        sql.SET("VoteDate = #{record.votedate,jdbcType=DATE}");
        
        VoteTokenExample example = (VoteTokenExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote_Token
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, VoteTokenExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}