package pers.adlered.voter.service;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Service;
import pers.adlered.voter.domain.VoteToken;
import pers.adlered.voter.domain.VoteTokenExample;

import java.util.Date;
import java.util.List;
@Service
public interface VoteTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote_Token
     *
     * @mbg.generated
     */
    @SelectProvider(type=VoteTokenSqlProvider.class, method="countByExample")
    long countByExample(VoteTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote_Token
     *
     * @mbg.generated
     */
    @DeleteProvider(type=VoteTokenSqlProvider.class, method="deleteByExample")
    int deleteByExample(VoteTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote_Token
     *
     * @mbg.generated
     */
    @Delete({
        "delete from Voter_Vote_Token",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote_Token
     *
     * @mbg.generated
     */
    @Insert({
        "insert into Voter_Vote_Token (VID, Token, ",
        "Selection, md5_v, ",
        "md5_m, crc, VoteDate)",
        "values (#{vid,jdbcType=INTEGER}, #{token,jdbcType=VARCHAR}, ",
        "#{selection,jdbcType=VARCHAR}, #{md5V,jdbcType=VARCHAR}, ",
        "#{md5M,jdbcType=VARCHAR}, #{crc,jdbcType=VARCHAR}, #{votedate,jdbcType=DATE})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(VoteToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote_Token
     *
     * @mbg.generated
     */
    @InsertProvider(type=VoteTokenSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(VoteToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote_Token
     *
     * @mbg.generated
     */
    @SelectProvider(type=VoteTokenSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="ID", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="VID", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="Token", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="Selection", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="md5_v", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="md5_m", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="crc", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="VoteDate", javaType=Date.class, jdbcType=JdbcType.DATE)
    })
    List<VoteToken> selectByExample(VoteTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote_Token
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "ID, VID, Token, Selection, md5_v, md5_m, crc, VoteDate",
        "from Voter_Vote_Token",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    @ConstructorArgs({
        @Arg(column="ID", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="VID", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="Token", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="Selection", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="md5_v", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="md5_m", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="crc", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="VoteDate", javaType=Date.class, jdbcType=JdbcType.DATE)
    })
    VoteToken selectByPrimaryKey(Integer id);

    /***
     *
     *
     * */
    @Select({
            "select",
            "ID, VID, Token, Selection, md5_v, md5_m, crc, VoteDate",
            "from Voter_Vote_Token",
            "where ID = #{id,jdbcType=INTEGER}"
    })
    @ConstructorArgs({
            @Arg(column="ID", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
            @Arg(column="VID", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
            @Arg(column="Token", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="Selection", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="md5_v", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="md5_m", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="crc", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="VoteDate", javaType=Date.class, jdbcType=JdbcType.DATE)
    })
    @Results({
            @Result(property="vote",column="VID",   one=@One(select="pers.adlered.voter.service.Vote1Mapper.selectByPrimaryKey"))
    })
    VoteToken selectVoteByPrimaryKey(Integer id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote_Token
     *
     * @mbg.generated
     */
    @UpdateProvider(type=VoteTokenSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") VoteToken record, @Param("example") VoteTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote_Token
     *
     * @mbg.generated
     */
    @UpdateProvider(type=VoteTokenSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") VoteToken record, @Param("example") VoteTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote_Token
     *
     * @mbg.generated
     */
    @UpdateProvider(type=VoteTokenSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(VoteToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote_Token
     *
     * @mbg.generated
     */
    @Update({
        "update Voter_Vote_Token",
        "set VID = #{vid,jdbcType=INTEGER},",
          "Token = #{token,jdbcType=VARCHAR},",
          "Selection = #{selection,jdbcType=VARCHAR},",
          "md5_v = #{md5V,jdbcType=VARCHAR},",
          "md5_m = #{md5M,jdbcType=VARCHAR},",
          "crc = #{crc,jdbcType=VARCHAR},",
          "VoteDate = #{votedate,jdbcType=DATE}",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(VoteToken record);
}