package pers.adlered.voter.service;

import org.apache.ibatis.jdbc.SQL;
import pers.adlered.voter.domain.Vote1;
import pers.adlered.voter.domain.Vote1Example;
import pers.adlered.voter.domain.Vote1Example.Criteria;
import pers.adlered.voter.domain.Vote1Example.Criterion;

import java.util.List;
import java.util.Map;

public class Vote1SqlProvider {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote
     *
     * @mbg.generated
     */
    public String countByExample(Vote1Example example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("Voter_Vote");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote
     *
     * @mbg.generated
     */
    public String deleteByExample(Vote1Example example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("Voter_Vote");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote
     *
     * @mbg.generated
     */
    public String insertSelective(Vote1 record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("Voter_Vote");
        
        if (record.getTitle() != null) {
            sql.VALUES("Title", "#{title,jdbcType=VARCHAR}");
        }
        
        if (record.getDescribes() != null) {
            sql.VALUES("Describes", "#{describes,jdbcType=VARCHAR}");
        }
        
        if (record.getSelection() != null) {
            sql.VALUES("Selection", "#{selection,jdbcType=VARCHAR}");
        }
        
        if (record.getType() != null) {
            sql.VALUES("Type", "#{type,jdbcType=INTEGER}");
        }
        
        if (record.getLimits() != null) {
            sql.VALUES("Limits", "#{limits,jdbcType=INTEGER}");
        }
        
        if (record.getPass() != null) {
            sql.VALUES("Pass", "#{pass,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote
     *
     * @mbg.generated
     */
    public String selectByExample(Vote1Example example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("VID");
        } else {
            sql.SELECT("VID");
        }
        sql.SELECT("Title");
        sql.SELECT("Describes");
        sql.SELECT("Selection");
        sql.SELECT("Type");
        sql.SELECT("Limits");
        sql.SELECT("Pass");
        sql.FROM("Voter_Vote");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Vote1 record = (Vote1) parameter.get("record");
        Vote1Example example = (Vote1Example) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("Voter_Vote");
        
        if (record.getVid() != null) {
            sql.SET("VID = #{record.vid,jdbcType=INTEGER}");
        }
        
        if (record.getTitle() != null) {
            sql.SET("Title = #{record.title,jdbcType=VARCHAR}");
        }
        
        if (record.getDescribes() != null) {
            sql.SET("Describes = #{record.describes,jdbcType=VARCHAR}");
        }
        
        if (record.getSelection() != null) {
            sql.SET("Selection = #{record.selection,jdbcType=VARCHAR}");
        }
        
        if (record.getType() != null) {
            sql.SET("Type = #{record.type,jdbcType=INTEGER}");
        }
        
        if (record.getLimits() != null) {
            sql.SET("Limits = #{record.limits,jdbcType=INTEGER}");
        }
        
        if (record.getPass() != null) {
            sql.SET("Pass = #{record.pass,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("Voter_Vote");
        
        sql.SET("VID = #{record.vid,jdbcType=INTEGER}");
        sql.SET("Title = #{record.title,jdbcType=VARCHAR}");
        sql.SET("Describes = #{record.describes,jdbcType=VARCHAR}");
        sql.SET("Selection = #{record.selection,jdbcType=VARCHAR}");
        sql.SET("Type = #{record.type,jdbcType=INTEGER}");
        sql.SET("Limits = #{record.limits,jdbcType=INTEGER}");
        sql.SET("Pass = #{record.pass,jdbcType=VARCHAR}");
        
        Vote1Example example = (Vote1Example) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(Vote1 record) {
        SQL sql = new SQL();
        sql.UPDATE("Voter_Vote");
        
        if (record.getTitle() != null) {
            sql.SET("Title = #{title,jdbcType=VARCHAR}");
        }
        
        if (record.getDescribes() != null) {
            sql.SET("Describes = #{describes,jdbcType=VARCHAR}");
        }
        
        if (record.getSelection() != null) {
            sql.SET("Selection = #{selection,jdbcType=VARCHAR}");
        }
        
        if (record.getType() != null) {
            sql.SET("Type = #{type,jdbcType=INTEGER}");
        }
        
        if (record.getLimits() != null) {
            sql.SET("Limits = #{limits,jdbcType=INTEGER}");
        }
        
        if (record.getPass() != null) {
            sql.SET("Pass = #{pass,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("VID = #{vid,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, Vote1Example example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}