package pers.adlered.voter.service;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import pers.adlered.voter.domain.VoteToken;
import pers.adlered.voter.domain.VoteTokenExample;

import java.util.Date;
import java.util.List;

public interface VoteTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote_Token
     *
     * @mbg.generated
     */
    @SelectProvider(type=VoteTokenSqlProvider.class, method="countByExample")
    long countByExample(VoteTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote_Token
     *
     * @mbg.generated
     */
    @DeleteProvider(type=VoteTokenSqlProvider.class, method="deleteByExample")
    int deleteByExample(VoteTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote_Token
     *
     * @mbg.generated
     */
    @Insert({
        "insert into Voter_Vote_Token (VID, Token, ",
        "Selection, md5_v, ",
        "md5_m, crc, VoteDate)",
        "values (#{vid,jdbcType=INTEGER}, #{token,jdbcType=VARCHAR}, ",
        "#{selection,jdbcType=VARCHAR}, #{md5V,jdbcType=VARCHAR}, ",
        "#{md5M,jdbcType=VARCHAR}, #{crc,jdbcType=VARCHAR}, #{votedate,jdbcType=DATE})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(VoteToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote_Token
     *
     * @mbg.generated
     */
    @InsertProvider(type=VoteTokenSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(VoteToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote_Token
     *
     * @mbg.generated
     */
    @SelectProvider(type=VoteTokenSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="ID", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="VID", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="Token", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="Selection", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="md5_v", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="md5_m", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="crc", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="VoteDate", javaType=Date.class, jdbcType=JdbcType.DATE)
    })
    List<VoteToken> selectByExample(VoteTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote_Token
     *
     * @mbg.generated
     */
    @UpdateProvider(type=VoteTokenSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") VoteToken record, @Param("example") VoteTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Voter_Vote_Token
     *
     * @mbg.generated
     */
    @UpdateProvider(type=VoteTokenSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") VoteToken record, @Param("example") VoteTokenExample example);
}